export const GET_ORDERS_REQUEST ="GET_ORDER_REQUEST";
export const GET_ORDERS_SUCCESS="GET_ORDERS_SUCCESS";
export const GET_ORDERS_FALIURE ="GET_ORDERS_FALIURE";


export const CONFIRMED_ORDER_REQUEST ="CONFIRMED_ORDER_REQUEST";
export const CONFIRMED_ORDER_SUCCESS="CONFIRMED_ORDER_SUCCESS";
export const CONFIRMED_ORDER_FALIURE ="CONFIRMED_ORDER_FALIURE";


export const PLACED_ORDER_REQUEST ="PLACED_ORDER_REQUEST";
export const PLACED_ORDER_SUCCESS="PLACED_ORDER_SUCCESS";
export const PLACED_ORDER_FALIURE ="PLACED_ORDER_FALIURE";


export const DELIVERED_ORDER_REQUEST ="DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS="DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FALIURE ="DELIVERED_ORDER_FALIURE";

export const CANCELED_ORDER_REQUEST ="CANCELED_ORDER_REQUEST";
export const CANCELED_ORDER_SUCCESS="CANCELED_ORDER_SUCCESS";
export const CANCELED_ORDER_FALIURE ="CANCELED_ORDER_FALIURE";

export const DELETE_ORDER_REQUEST ="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FALIURE ="DELETE_ORDER_FALIURE";

export const SHIP_ORDER_REQUEST ="SHIP_ORDER_REQUEST";
export const SHIP_ORDER_SUCCESS="SHIP_ORDER_SUCCESS";
export const SHIP_ORDER_FALIURE ="SHIP_ORDER_FALIURE";


