// src/actions/types.js

export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const UPDATE_WISHLIST_COUNT ='UPDATE_WISHLIST_COUNT'
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS'